import "@/app/globals.css";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/universal/Navbar";
// import AuthProvider from "./context/AuthProvider";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionProvider>
      <body>
        <Navbar />
        {children}
        <Toaster />
      </body>
      </SessionProvider>
    </html>
  );
}
